name: Build for Android

on:
  [pull_request, push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build ${{matrix.arch}}"

    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: "${ANDROID_SDK_ROOT}/ndk-bundle"

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako ninja
          mkdir -p /tmp/build/lib/pkgconfig
          cp libdrm.pc /tmp/build/lib/pkgconfig/
          wget https://github.com/Vera-Firefly/libepoxy/raw/master/include/EGL/eglplatform.h -P EGL
          wget https://github.com/Vera-Firefly/libepoxy/raw/master/include/KHR/khrplatform.h -P KHR

      - name: Download NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip android-ndk-r26b-linux.zip

      - name: Build libepoxy
        run: |
          git clone --depth 1 https://github.com/Vera-Firefly/libepoxy.git
          cd libepoxy
          meson "build-android-${{matrix.arch}}" \
            --prefix=/tmp/build \
            --cross-file "../android-${{matrix.arch}}" \
            -Degl=yes -Dglx=no -Dx11=false
          ninja -C "build-android-${{matrix.arch}}" install

      - name: Build virglrenderer
        run: |
          git clone --shallow-since 2022-06-27 https://gitlab.freedesktop.org/virgl/virglrenderer
          cd virglrenderer
          wget https://cdn.discordapp.com/attachments/755410958100201472/1197617470597505094/vtest-patch.diff
          git apply -v --rej ./vtest-patch.diff
          meson "build-android-${{matrix.arch}}" \
            --prefix=/tmp/build \
            --cross-file "android-${{matrix.arch}}" \
            -Dplatforms=egl \
            -Dc_args='-Wno-error=gnu-offsetof-extensions'
          ninja -C "build-android-${{matrix.arch}}" install
          cp "build-android-${{matrix.arch}}/vtest/libvirgl_test_server.so" /tmp/build/lib/

      - name: Change suffix
        run: |
          cd /tmp/build/lib
          rm libepoxy.so libepoxy.so.0 libvirglrenderer.so libvirglrenderer.so.1
          mv libepoxy.so.0.* libepoxy_0.so
          mv libvirglrenderer.so.1.* libvirglrenderer_1.so
          perl -pi -e 's/libepoxy.so.0/libepoxy_0.so/g' *.so
          perl -pi -e 's/libvirglrenderer.so.1/libvirglrenderer_1.so/g' *.so ../bin/*
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: build_${{matrix.arch}}
          path: /tmp/build
